---
# File: site.yml - Example Consul site playbook

- name: Roles and Task run on localhost 
  hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    - name: Clean artifact path
      file:
        state: absent
        path: ~/.ssh/known_hosts
  roles:
    - { role: clc, tags: ['create_server'] }

- name: Roles and Task run on all servers
  hosts: all
  gather_facts: false
  remote_user: root
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: hosts_files, tags: all_hosts_files, host_servers: "{{ hostvars.localhost.all_servers }}" }

- name: Roles and Task run on localhost
  hosts: localhost
  gather_facts: False
  connection: local
  roles:
    - { role: hosts_files, tags: localhost_hosts_files, host_servers: "{{ hostvars.localhost.all_servers }}" }
  tasks: 
    - name: print all groups info
      debug:
        msg: "{{ groups }}"

- name: Assemble Consul, Nomad, dnsmasq, docker cluster
  hosts: cluster_nodes
  #hosts: consul_instances
  gather_facts: true 
  remote_user: root
  any_errors_fatal: true
  become: yes
  become_user: root
  roles:
    - { role: ssh-keys, tags: ssh-keys }
    - { role: os-setup, tags: os-setup }
    - { role: kbrebanov.ntp, tags: ntp }
    - { role: docker-ce, tags: docker }
    - { role: lxd, tags: lxd }
    - { role: andrewrothstein.consul-template, tags: consul-template }
    - { role: brianshumate.consul, tags: 'consul' }
    - { role: brianshumate.vault, tags: 'vault' }
    - { role: brianshumate.nomad, tags: 'nomad' }

#    - { role: lobsterdore.fabio, fabio_version: 1.5.0, tags: 'fabio' }
  
