- name: configure lxd bridge
  template: src=lxd-bridge.j2 dest=/etc/default/lxd-bridge mode=0644 backup=yes
  notify:
    - reconfigure lxd
    - restart lxd-bridge
  register: lxdconf

- name: force restart of lxd to have working network
  service: name=lxd state=restarted
  notify:
    - reconfigure lxd
    - restart lxd-bridge
  when: lxdconf.changed and (ansible_virtualization_type is not defined or ansible_virtualization_type != "lxc")
