---
# File: main.yml - Main tasks for Consul
#
# Unfortunately, this playbook violates DRY somewhat to handle installation
# on both non-Windows and Windows systems due to such bad words as casting
# dicts, and being so over YAML that this stuff just needs to get pitched
# into the rubbish bin at some point in the immediate future :lol:


   
#############################################################################
# Tasks for all *NIX operating systems
#############################################################################

#get images and create container

- name: list existing lxc images
  command: "lxc image list"
  changed_when: false
  register: imagelist
  #when: server_role == 'client' or server_role == 'both'

- name: pre copy lxc images
  include: "lxc-image-copy.yml current={{ imagelist }} image={{ item.i }} alias={{ item.alias }}"
  with_items: "{{ lxd_preloadimages }}"
  #when: server_role == 'client' or server_role == 'both'

- name: list existing lxc images
  command: "lxc image list"
  changed_when: false
  register: imagelist2
  #when: server_role == 'client' or server_role == 'both'

- name: list existing lxc instances
  command: "lxc info alpine-demo"
  changed_when: false
  register: lxclist
  #when: server_role == 'client' or server_role == 'both'
  ignore_errors: yes

- name: preconfigure lxc containers cli
  command: "lxc launch images:alpine/3.5 alpine-demo"
  register: lxclaunch
  when: lxclist.rc|int != 0
  #when: server_role == 'client' or server_role == 'both' and lxclist.rc|int != 0
  ignore_errors: yes
  when: lxclist.rc|int != 0

#- name: preconfigure lxc containers
#  include: "lxc-createcontainers.yml guest={{ outer_item.guest }} template={{ outer_item.template }}"
#  with_items: "{{ lxd_preconfigure }}"
#  loop_control:
#    loop_var: outer_item
#  when: server_role == 'client' or server_role == 'both'

#- name: Start LXD
#  service:
#    name: lxd
#    enabled: yes
#    state: started



#############################################################################
# End of tasks for all *NIX operating systems
#############################################################################
