---

#- name: force restart of lxd to have working network
#  service: name=lxd state=restarted
#  notify:
#    - reconfigure lxd
#    - restart lxd-bridge
#  when: lxdconf.changed and (ansible_virtualization_type is not defined or ansible_virtualization_type != "lxc")

- name: get raw unused disk for zfs pool
  shell: "parted -ml 2>&1 |grep Error |cut -d: -f2"
  register: raw_disk

- name: debug raw_disk
  debug:
    var: raw_disk

- name: setfacts lxd_zfs_pool_name
  set_fact:
    lxd_zfs_pool_name: lxdpool1
    lxd_bridge_name: testbr0

- name: lxc network show 
  command: lxc network show {{ lxd_bridge_name }}
  register: lxd_network_exist
  ignore_errors: true

- name: debug lxd_network_exist
  debug:
    var: lxd_network_exist

# Bridge setup
- name: create initial lxd bridge
  command: lxc network create {{ lxd_bridge_name }} ipv6.address=none ipv4.address=10.0.3.1/24 ipv4.nat=true dns.domain=cgm
  register: lxc_create_bridge_profile
  when: lxd_network_exist.rc|int != 0
  ignore_errors: true

- name: check if bridge is attach to default profile
  command: lxc profile show default |grep {{ lxd_bridge_name }}
  register: lxc_info_bridge_profile
  #when: lxd_network_exist.rc|int != 0
  ignore_errors: true

- name: debug lxc_info_bridge_profile
  debug:
    var: lxc_info_bridge_profile

- name: add lxd bridge to default profile
  command: lxc network attach-profile {{ lxd_bridge_name }} default eth0
  register: lxc_add_bridge_profile
  when: lxc_info_bridge_profile|int != 0
  ignore_errors: true

# ZFS setup

- name: verify if ZFS pool exists
  shell: zpool list {{ lxd_zfs_pool_name }}
  register: zfspool
  ignore_errors: true

- name: print zfspool
  debug: var=zfspool

- name: create zfs storage pool
  command: lxc storage create {{ lxd_zfs_pool_name }} zfs "source={{ raw_disk.stdout }}"
  register: lxc_create_zfs_pool
  when: zfspool.rc|int != 0
  ignore_errors: true

- name: check if zfs pool is attached default profile
  command: lxc profile show default |grep {{ lxd_zfs_pool_name }}
  register: lxc_info_zfs_pool_profile
  ignore_errors: true

- name: debug lxc_info_zfs_pool_profile
  debug: 
    var: lxc_info_zfs_pool_profile

- name: attach zfs pool to default profile
  command: lxc profile device add default root disk path=/ pool={{ lxd_zfs_pool_name }}
  register: lxc_add_zfs_profile
  when: lxc_info_zfs_pool_profile.rc|int != 0
  ignore_errors: true

