---
#- name: configure lxd bridge
#  template: src=lxd-bridge.j2 dest=/etc/default/lxd-bridge mode=0644 backup=yes
#  notify:
#    - reconfigure lxd
#    - restart lxd-bridge
#  register: lxdconf

#- name: force restart of lxd to have working network
#  service: name=lxd state=restarted
#  notify:
#    - reconfigure lxd
#    - restart lxd-bridge
#  when: lxdconf.changed and (ansible_virtualization_type is not defined or ansible_virtualization_type != "lxc")

- name: setfacts lxd_zfs_pool_name
  set_fact:
    lxd_zfs_pool_name: lxdpool1
    lxd_bridge_name: testbr0
- name: 
  command: lxc network show testbr0
  register: lxd_network_exist
  ignore_errors: true

# Bridge setup
- name: create initial lxd bridge
  command: lxc network create testbr0 ipv6.address=none ipv4.address=10.0.3.1/24 ipv4.nat=true dns.domain=cgm
  register: lxc_create_bridge_profile
  when: lxd_network_exist.rc|int != 0
  ignore_errors: true

- name: add lxd bridge to default profile
  command: lxc network attach-profile testbr0 default eth0
  register: lxc_add_bridge_profile
  when: lxc_create_bridge_profile.rc|int == 0
  ignore_errors: true

# ZFS setup

- name: verify if ZFS pool exists
  shell: zpool list {{ lxd_zfs_pool_name }}
  register: zfspool
  ignore_errors: true

- name: print zfspool
  debug: var=zfspool

- name: create zfs storage pool
  command: lxc storage create {{ lxd_zfs_pool_name }} zfs source=/dev/sdd
  register: lxc_create_zfs_pool
  when: lxc_create_zfs_pool.rc|int != 0
  ignore_errors: true

- name:
  command: lxc profile device add default root disk path=/ pool={{ lxd_zfs_pool_name }}
  register: lxc_add_zfs_profile
  when: lxc_create_zfs_pool.rc|int == 0
  ignore_errors: true

#- name: create zfs file for lxd of 10GB
#  command: "truncate -s 10G /usr/lib/lxd/zfs.img"
#  when: zfspool.rc|int != 0

#- name: create new zpool for lxd
#  command: "zpool create {{ lxd_zfs_pool_name }} /usr/lib/lxd/zfs.img"
#  when: zfspool.rc|int != 0

#- name: verify if lxd is configured to use ZFS
#  shell: lxc info | grep storage | grep zfs
#  register: lxcinfo
#  ignore_errors: true

#- name: check if zfs pool setup in lxd
#  shell: "lxc storage show {{ lxd_zfs_pool_name }}"
#  register: lxcinfo
#  ignore_errors: true

#- name: lxcinfo result
#  debug: var=lxcinfo

#- name: lxxd zfs pool
#  debug: var=lxd_zfs_pool_name

#- name: configure lxd to use zfs
#  command: "lxd init --storage-backend zfs --storage-pool {{ lxd_zfs_pool_name }} --auto"
#  when: lxcinfo.rc|int != 0


