---
# tasks file for ansible-module-lxd

- name: "download lxc image: {{ image }}"
  command: "lxc image copy {{ image }} local: --alias={{ alias }}"
  when: current is defined and current.stdout.find(alias) == -1