---
# File: main.yml - Main tasks for Consul
#
# Unfortunately, this playbook violates DRY somewhat to handle installation
# on both non-Windows and Windows systems due to such bad words as casting
# dicts, and being so over YAML that this stuff just needs to get pitched
# into the rubbish bin at some point in the immediate future :lol:


   
#############################################################################
# Tasks for all *NIX operating systems
#############################################################################

- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install lxd, zfs, bridge and other software packages
  include: "{{ ansible_os_family }}.yml"
  #when: nomad_docker_enable | bool
  when: server_role == 'client' or server_role == 'both'

- name: Include initial setup bridge, zfs
  include: initial-setup.yml
  when: server_role == 'client' or server_role == 'both'

- name: Include lxd add images, create demo container
  include: image_container.yml
  when: server_role == 'client' or server_role == 'both'

#- name: Start LXD
#  service:
#    name: lxd
#    enabled: yes
#    state: started


#############################################################################
# End of tasks for all *NIX operating systems
#############################################################################
