---
- name: verify if ZFS pool exists
  shell: zpool list {{ lxd_zfs_pool_name }}
  register: zfspool
  ignore_errors: true

- name: print zfspool
  debug: var=zfspool

- name: create zfs file for lxd of 10GB
  command: "truncate -s 10G /usr/lib/lxd/zfs.img"
  when: zfspool.rc != 0

- name: create new zpool for lxd
  command: "zpool create {{ lxd_zfs_pool_name }} /usr/lib/lxd/zfs.img"
  when: zfspool.rc != 0

- name: verify if lxd is configured to use ZFS
  shell: lxc info | grep storage | grep zfs
  register: lxcinfo
  ignore_errors: true

- name: configure lxd to use zfs
  command: "lxd init --storage-backend zfs --storage-pool {{ lxd_zfs_pool_name }} --auto"
  when: lxcinfo.rc != 0

