---
- name: Install docker helper  packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
  tags:
    - docker

- name: add docker repository key
  apt_key:
    url: "{{ apt_key_url }}"
    state: present
  tags:
    - docker

- name: add docker repository 
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present
  tags:
    - docker

- name: apt - Update ubuntu
  apt:
    update_cache: yes
  register: apt_update
  tags:
    - docker

- name: Install docker-ce packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
  tags:
    - docker

- name: upgrade latest docker-py
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: docker-py, version: "{{ docker_py_version }}", install: "{{ docker_py_install }}" }
  when: (item.version=="latest" and item.install)
  tags:
    - docker

- name: start docker
  service:
    name: docker
    state: started

- name: update facts if docker0 is not defined
  action: setup filter="ansible_docker0"
  when: ansible_docker0 is not defined

