---
- name: Install ansible deployer
  hosts: localhost
  vars:
    apt_packages:
    - vim
    - curl
    - git
    - s3curl
    - s3cmd
    - ansible
    - vim-nox-py2
    - python-pip
    - unzip
    pip_packages:
    - ipython
    - pylxd
    - boto
    - virtualenv

  tasks:
    - name: Say Hello
      shell: echo "Hello World!"
    - name: Apt Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ apt_packages }}"
      register: apt_results
      tags:
        - apt

    - name: pip Install packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ pip_packages }}"
      register: pip_results
      tags:
        - pip

    - name: git clc-sdk
      git:
        repo: https://github.com/CenturyLinkCloud/clc-python-sdk.git
        dest: /srv/checkout


