---
- hosts: localhost
  vars:
    apt_packages:
    - vim
    - curl
    - git
    - s3curl
    - s3cmd
    - ansible
    - vim-nox-py2
    - python-pip
    - python-netaddr

    pip_packages:
    - jupyter
    - pylxd
    - boto
    - netaddr
    - virtualenv

  tasks:
    - name: Apt Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ apt_packages }}"
      register: apt_results
      tags:
        - apt

    - name: pip upgrade
      shell: pip install --upgrade pip
      register: Pip_upgrade   

    - name: pip Install packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ pip_packages }}"
      register: pip_results
      tags:
        - pip

    - name: git clc-sdk
      git:
        repo: https://github.com/CenturyLinkCloud/clc-python-sdk.git
        dest: /srv/clc-python-sdk
      tags:
        - git_clc_sdk

    - name: pip install clc-python-sdk
      pip:
        name: /srv/clc-python-sdk/src
      tags:
        - pip_clc_sdk

    - name: git clc-ansible-module
      git:
        repo: git://github.com/CenturyLinkCloud/clc-ansible-module.git
        dest: /srv/clc-ansible-module
      tags:
        - git_clc_ansible

    - name: pip install clc-ansible-module
      pip:
        name: /srv/clc-ansible-module
      tags:
        - pip_clc_ansible

    - name: "Ansible copy files remote to remote"
      copy:
        src: files/myenv.sh      
        dest: /etc/profile.d
        remote_src: yes
      tags:
        - myenv

    - name: Append validate_certs to hasicorp download
      shell: "sed -i '/^  local_action: get_url url/ s/$/ validate_certs no/' {{ item }}"
      run_once: True
      with_items:
      - /etc/ansible/roles/brianshumate.consul/tasks/install.yml
      - /etc/ansible/roles/brianshumate.nomad/tasks/install.yml
      - /etc/ansible/roles/brianshumate.vault/tasks/install.yml
      tags:
        - validate_certs


