---
- name: apt - Update and upgrade ubuntu
  apt:
    upgrade: dist
    update_cache: yes
  async: 1000
  poll: 0
  register: apt_upgraderesults

- name: 'Apt wait upgrade to complete'
  async_status: jid={{ apt_upgraderesults.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 300

- name: Autoremove - Remove dependencies that are no longer required
  command: apt-get -y autoremove
  register: autoremove_output
  changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"

- name: Apt Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ apt_packages }}"
  register: apt_results

